### ISSUE TITLE
Config order for Iceberg tables

### ISSUE THREAD

**Issue by talhasenSC** [dbt-athena/dbt-athena#495] opened 2023-11-07 17:44 UTC
I have recently encountered this issue when I tried to run a dbt model with the following config:

```
{{
    config(
        table_type='iceberg',
        materialized='incremental',
        incremental_strategy='merge',
        unique_key='id',
        schema='some_schema',
        ...
    )   
 }}
```

The error:
```
Running with dbt=1.6.7
Registered adapter: athena=1.6.4
...
Encountered an error:
argument of type 'NoneType' is not iterable
```

This config used to work successfully.
I figured out the reason of this issue is the order of `table_type` and `materialized`. 

And it is solved with the following config:
```
{{
    config(
        materialized='incremental',
        table_type='iceberg',
        incremental_strategy='merge',
        unique_key='id',
        schema='some_schema',
        ...
    )   
 }}
```

Is this expected or a bug?

**Comment by svdimchenko** [comment] 2023-11-07 20:35
@talhasenSC I'm wondering if the issue is now fixed with https://github.com/dbt-athena/dbt-athena/commit/e398aecc4e78385cc79c5d0c503c0164b73efbc0, could you check that please?

**Comment by nicor88** [comment] 2023-11-09 08:46
@talhasenSC do you have more input on this issue? does release 1.6.4 of dbt-athena-community fix your issue?

**Comment by talhasenSC** [comment] 2023-11-09 17:40
I couldn't reproduce the issue again, will update if happens again

**Closed** 2023-11-10 08:05 UTC
Labels: bug
