### ISSUE TITLE
Iceberg table support 

### ISSUE THREAD

**Issue by zsvoboda** [dbt-athena/dbt-athena#19] opened 2022-11-11 19:06 UTC
Hi, 

I'm looking at the Iceberg tables support plan:

As iceberg doesn't support CTA, the implementation do the following:

- create tmp table as parquet
- drop the old table, if exist
- create iceberg table based on tmp table definition, only metadata
- insert into from tmp
- drop tmp table

I think that the tmp table creation is going to kill performance (I have 10s of billions of rows). 

How about this approach:

1. create the tmp table with the model's SELECT with "LIMIT 0" appended
2. create iceberg table based on tmp table definition, only metadata
3. insert into the iceberg table with the model's SQL (don't append the LIMIT this time) 
4. drop the tmp table 

This would save one copying of all rows (hours of processing in my case). 

Regards, 

ZD

**Comment by nicor88** [comment] 2022-11-11 20:25
That could indeed work. Should be an easy change, I will try to add that to the original implementation.

**Comment by nicor88** [comment] 2022-11-11 20:43
@zsvoboda this issue is duplicate of https://github.com/dbt-athena/dbt-athena/issues/11 could you add your comment there please? Then I will close this one.

**Closed** 2022-11-11 20:46 UTC
